# Name of your GitHub Actions workflow
name: Update Chartink Data

# Controls when the action will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Runs on a schedule
  schedule:
    # This runs the job every 10 minutes
    - cron: '*/10 * * * *'

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checks-out your repository
      - name: Check out repository
        uses: actions/checkout@v4

      # Step 2: Set up the Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Step 3: Install dependencies directly <-- THIS IS THE MODIFIED STEP
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas beautifulsoup4

      # Step 4: Run your Python script
      - name: Run the Chartink data script
        run: python scripts/chartink.py

      # Step 5: Commit the updated data file
      - name: Commit and push if there are changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated update of Chartink data"
          file_pattern: "static/data/Chartink.json"
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "actions@github.com"```

### What Changed?

The only part that is different is Step 3.

**Instead of this:**
```yaml
- name: Install dependencies
  run: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
