name: Run Historical Data Collector

permissions:
  contents: write   # ✅ Needed to push commit

on:
  schedule:
    - cron: '30 0 * * *' # 6 AM IST
  workflow_dispatch:

jobs:
  run-historical-script:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: scripts

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 🐍 Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - name: 📦 Install dependencies
        run: |
          pip install requests
          
      - name: 🚀 Run Historical_Data.py
        run: python Historical_Data.py

      - name: 💾 Commit & Push updated file
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add stock_historical_universe.json
          git diff --staged --quiet || git commit -m "📈 Auto-update historical data at $(TZ='Asia/Kolkata' date '+%Y-%m-%d %H:%M:%S IST')"
          git push
